language: python
python:
  - "3.7"
cache: pip
install:
  - pip install freeze
  - pip freeze > requirements.txt
  - ls -al
  - pip install -r requirements.txt
  - pip install pipreqs
  - pipreqs 
  - ls -al
  - cat requirements.txt
script:
